apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::382160405476:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::382160405476:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-9NQ2ZW8J085N
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-10T20:49:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1339"
  uid: f2673996-b5e9-4dd1-a6db-d9de3e399f22
